GET http://localhost:8080/ HTTP/1.1

###
POST http://localhost:8080/api/auth HTTP/1.1
Content-Type: application/json

{
  "credentials": {
    "email":"xx@xyz.com",
    "password": "123"
  }
}

###
POST http://localhost:8080/api/user HTTP/1.1
Content-Type: application/json

{
  "user": {
    "email": "tabvim.dev@gmail.com",
    "password": "1"
  }
}

###
POST http://localhost:8080/api/auth/confirmation HTTP/1.1
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Inh4eHhAeHguY2MiLCJpYXQiOjE1Mjc2NjQzODN9.pX81f1pQNI3BpLDyvgtrseO3MQnixFMhuCIZ7QoJtYQ"
}

###
POST http://localhost:8080/api/user/reset_pass HTTP/1.1
Content-Type: application/json

{
  "credentials": {
    "email": "tabvim.dev@gmail.com",
    "password": "2",
    "new_password": "1"
  }
}

###
GET http://localhost:8080/api/books/search HTTP/1.1
Content-Type: application/json

###
POST http://localhost:8080/api/books/search HTTP/1.1
Content-Type: application/json
authorization: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRhYnZpbS5kZXZAZ21haWwuY29tIiwiY29uZmlybSI6dHJ1ZSwiaWF0IjoxNTI4MDczNDgzfQ.MfCtfaroDjOkFYogJUXR7nbNLZB3NCOQOxQO-EqaDa4" 

{
  "book": {
    "title": "JavaScript: The Good Parts",
    "page": 123,
    "cover": "http://xxxxxx"
  }
}